### ISSUE TITLE
[FR] Support multiple master channels

### ISSUE THREAD

**Issue by shejialuo** [ehForwarderBot/ehForwarderBot#293]
**Is your feature request related to a problem? Please describe.**  
Now the EFB framework only supports one master channel. If someone needs another master channel, for example, `efb-telegram-master`, one for QQ and one for WeChat for different telegram bots, someone needs to run another `efb` process specified with the corresponding profile. It needs run the same instance of the master channel and middlewares which costs more memory and makes the configuration cumbersome.

**Describe the solution you'd like**  
Now the framework only supports one master channel. And channels uses `coordinator.send_message` method to send the messages between channels. Due to the only one master channel, the logic is simple. However, I think we could make more master channels. But the trick thing here is that when we have two telegram bots, should we run only one `efb-telegram-master` instance or two? And how to distinguish the two instances if we run two instances? And if we run one instance, how to distinguish the two telegram bots. So for the same master channel, it would be more complicated. But for totally different master channels. We can easily distinguish by the name of the channel.

**Describe alternatives you've considered**  
I am not familiar with Python, I don't know whether the duplicate masters or middlewares can share the same memory. If we could make the same master channels or middlewares share the same memory `text` code, there would be no problem.

**Additional context**  
Thanks for your wonderful framework. I have used a few days to learn the source code. I really appreciate your code, which makes me learn a lot of things. The idea of this simple and beautiful framework is really amazing.

**Comment by blueset** [comment]
As you mentioned, currently we require each profile to have only one master channel as a part of the architecture design of EFB. For the use caes you described, you want to have two different master channels, each serves a different set of slave channels. In this case each master channel is working on a different set of chats and messages, and communicating with the user with a separate channel. 

Unless there is a need to have multiple master channels to work with one single slave channel – which would not make much sense – it is much easier to manage with multiple profiles running on different processes.

In term of memory consumption, since the chats, messages and the user communications are all totally different, there isn’t much we can share between two different profiles. Even if we run the two profiles in the same process, I do not see there would be any significant improvement in terms of memory consumption.

If memory consumption is critical, having multiple slave channels running under the same master channel is also a choice.
